micronaut:
    application:
        name: relibras
    router:
        static-resources:
                videos:
                    enabled: true
                    mapping: /static/**
                    paths: classpath:public